### ISSUE TITLE
Allons! → Allons.

### ISSUE THREAD

**Issue by thewchan** [b-t-k/oliver-goldsmith_she-stoops-to-conquer#3]
`act-1.xhtml` line 334: According to page scans `<i xml:lang="fr">Allons</i>!` should be `<i xml:lang="fr">Allons</i>.`

**Comment by b-t-k** [comment]
Wow, that's a lot of proofing. I admit I played a little fast and easy with fixing the punctuation to match the new scans. A couple of times I used my own judgement (like in this case.)

**Comment by thewchan** [comment]
I wondered about this one as well, might be an Alex question

**Comment by thewchan** [comment]
@b-t-k also I'm mostly just review all the commits marked as editiorial, those transcription discrepancies may be present elsewhere too

**Comment by b-t-k** [comment]
Well thanks for the close read. Updating transcriptions gets hard when you are focussed on words and skip the small bits.
