### ISSUE TITLE
Song in act 1

### ISSUE THREAD

**Issue by thewchan** [b-t-k/oliver-goldsmith_she-stoops-to-conquer#4]
The title of the song (The Three Pigeons) in `act-1.xhtml` line 367 should be italicized as per https://standardebooks.org/manual/1.6.3/8-typography#8.2.11.2. I think with the `epub:type="z3998:song"` semantics.

**Comment by thewchan** [comment]
Likewise; `Water Parted` and `The Minuelt in Ariadne` seems to meet the criteria of "standalone" work, so instead of being quoted they should be italicized instead (with the proper semantics). See https://standardebooks.org/manual/1.6.3/8-typography#8.2.11

**Comment by b-t-k** [comment]
The Three Pigeons is the name of the tavern :-) And no, songs are in quotes not itlaics.
