### ISSUE TITLE
Act 4 discrepencies 

### ISSUE THREAD

**Issue by thewchan** [b-t-k/oliver-goldsmith_she-stoops-to-conquer#9]
Act 4 line 119:

`"She's mine, you rogue you..."` → `"She's mine, you rogue, you..."`

According to page scans

**Comment by thewchan** [comment]
line 251

`"I ordered them not to spare the cellar. I did, I assure you."` → `"I ordered them not to spare the cellar; I did, I assure you."`

**Comment by thewchan** [comment]
line 277

`"Good liquor will sit upon a good supper, but a good supper will not sit upon⁠—⁠hiccup⁠—⁠on my conscience, sir."` → `"Good liquor will sit upon a good supper, but a good supper will not sit upon⁠—⁠hiccup⁠—⁠upon my conscience, sir."`

**Comment by thewchan** [comment]
line 285

`"Zounds! he’ll drive me distracted, if I contain myself any longer. Mr. Marlow, Sir; I have submitted to your insolence for more than four hours, and I see no likelihood of its coming to an end. I’m now resolved to be master here, sir; and I desire that you and your drunken pack may leave my house directly."` → `"Zounds! he’ll drive me distracted, if I contain myself any longer. Mr. Marlow, Sir! I have submitted to your insolence for more than four hours, and I see no likelihood of its coming to an end. I’m now resolved to be master here, sir, and I desire that you and your drunken pack may leave my house directly."`

**Comment by thewchan** [comment]
Line 289:

`"Leave your house!⁠—⁠Sure you jest, my good friend! What? when I’m doing what I can to please you."` → "`Leave your house!⁠—⁠Sure you jest, my good friend? What? when I’m doing what I can to please you!"`

**Comment by thewchan** [comment]
Line 297:

`"Sure you cannot be serious? At this time of night, and such a night? You only mean to banter me."` → `"Sure you cannot be serious? at this time of night, and such a night? You only mean to banter me."`

**Comment by thewchan** [comment]
line 309:

`"Nor I, confound me if ever I did. To come to my house, to call for what he likes, to turn me out of my own chair, to insult the family, to order his servants to get drunk, and then to tell me, “This house is mine, sir.”..."` → `"Nor I, confound me if ever I did! To come to my house, to call for what he likes, to turn me out of my own chair, to insult the family, to order his servants to get drunk, and then to tell me, “This house is mine, sir!”..."`

**Comment by thewchan** [comment]
line 341:

`"Young man, young man, from your father’s letter to me, I was taught to expect a well-bred modest man as a visitor here..."` → `"Young man, young man, from your father’s letter to me, I was taught to expect a well-bred, modest man as a visitor here"`

**Comment by thewchan** [comment]
Line 397:

`"So then, all’s out, and I have been damnably imposed on. Oh, confound my stupid head, I shall be laughed at over the whole town....There again, may I be hanged, my dear, but I mistook you for the barmaid."` → `"So, then, all’s out, and I have been damnably imposed on. Oh, confound my stupid head, I shall be laughed at over the whole town!...There, again, may I be hanged, my dear, but I mistook you for the barmaid."`

**Comment by thewchan** [comment]
line 429:

`"This simplicity bewitches me, so that if I stay, I’m undone....Your partiality in my favour, my dear, touches me most sensibly: and were I to live for myself alone,..."` → `"This simplicity bewitches me so, that if I stay I’m undone....Your partiality in my favour, my dear, touches me most sensibly; and were I to live for myself alone,..."`

**Comment by thewchan** [comment]
line 439:

``I never knew half his merit till now. He shall not go, if I have power or art to detain him. I’ll still preserve the character in which I stooped to conquer; but will undeceive my papa, who perhaps may laugh him out of his resolution."` → `"I never knew half his merit till now. He shall not go if I have power or art to detain him. I’ll still preserve the character in which I stooped to conquer; but will undeceive my papa, who, perhaps may laugh him out of his resolution."`

**Comment by thewchan** [comment]
Line 463:

"`Here she comes, we must court a bit or two more, for fear she should suspect us."` → `"Here she comes; we must court a bit or two more, for fear she should suspect us."`

**Comment by thewchan** [comment]
Line 541:

`"I could wish to know though."` → `"I could wish to know, though."`

**Comment by thewchan** [comment]
Lime 565:

`"I cannot tell."` → `"I cannot tell!"`

**Comment by thewchan** [comment]
Line 581:

`"it’s all about cocks and fighting;..."` → `"it’s all about cocks, and fighting;..."`

**Comment by thewchan** [comment]
line 585

`"But I tell you, miss, it’s of all the consequence in the world."` → `"But I tell you, miss, it’s of all the consequence in the world!"`

**Comment by thewchan** [comment]
Line 589:

`"I’m now waiting for Miss Neville, with a post chaise and pair,...your mother, will otherwise suspect us!" → `"I’m now waiting for Miss Neville with a post chaise and pair,...your mother, will otherwise suspect us."`

**Comment by thewchan** [comment]
line 597:

`"Fine spoken, madam,...with scarce sense enough to keep your mouth shut: were you, too, joined against me?...I’ll show you, that I wish you better than you do yourselves."` → `"Fine spoken, madam;...with scarce sense enough to keep your mouth shut,—were you too joined against me?...I’ll show you that I wish you better than you do yourselves."`

**Comment by thewchan** [comment]
Line 747:

`">Pray be pacified. If I leave you thus, I shall die with apprehension."` → `">Pray, be pacified. If I leave you thus, I shall die with apprehension!"`

**Comment by thewchan** [comment]
Line 783:

`"Miss Neville! Constance! why Constance, I say!"` → `"Miss Neville! Constance! why, Constance, I say!"`

**Comment by thewchan** [comment]
Line 787:

`"I’m coming. Well, constancy, remember, constancy is the word."` → `"I’m coming! Well, constancy. Remember, constancy is the word."`

**Comment by thewchan** [comment]
Line 805:

`" Ecod, I have hit it. It’s here. Your hands. Yours and yours, my poor Sulky!...Meet me two hours hence at the bottom of the garden;...and Bet Bouncer into the bargain."` → `" Ecod, I have hit it. It’s here! Your hands. Yours, and yours, my poor Sulky....Meet me, two hours hence, at the bottom of the garden;...and Bet Bouncer into the bargain!"`

**Comment by b-t-k** [comment]
I made all the changes except one I think where the original was in fact more clear than the new edition.
